/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useState, useEffect } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inbox, Bell, NovuProvider, useNotifications } from "@novu/react";
import { dark } from "@novu/react/themes";
import "./globals.css";

function BellComponent({ unreadCount }: { unreadCount?: number }) {
  const hasUnread = unreadCount && unreadCount > 0;

  console.log("BellComponent RENDER - unreadCount:", unreadCount, "hasUnread:", hasUnread, "timestamp:", new Date().toISOString());

  return (
    <div className={`px-4 py-2 text-sm inline-flex items-center gap-2 rounded-lg transition-colors ${hasUnread ? "bg-blue-500" : "bg-gray-500"}`}>
      <span className="text-white">Notifications</span>
      {hasUnread && <span className="bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">{unreadCount}</span>}
    </div>
  );
}

function InboxWithBell() {
  const { notifications } = useNotifications();
  const unreadCount = notifications?.filter((n: any) => !n.isRead).length || 0;

  console.log("InboxWithBell - Total notifications:", notifications?.length, "Unread:", unreadCount);

  const [isDarkMode, setIsDarkMode] = useState(true);

  const appearance = {
    elements: {
      notification: ({ notification }: { notification: any }) => {
        return "";
      },
    },
  };

  return (
    <>
      <button
        onClick={() => setIsDarkMode(!isDarkMode)}
        className="px-4 py-2 text-sm rounded-lg bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
      >
        {isDarkMode ? "Light Mode" : "Dark Mode"}
      </button>
      <Inbox
        applicationIdentifier="Q9j-2L1WHqKP"
        subscriberId="e7b9d077-b16f-4c26-8382-4caf4b0ac084"
        appearance={isDarkMode ? { baseTheme: dark, ...appearance } : appearance}
        renderBell={() => <BellComponent unreadCount={unreadCount} />}
      />
    </>
  );
}

// const appearance = {
//   variables: {
//     // colorBackground: "#EDC2F2",
//     // borderRadius: "8px",
//     colorPrimaryForeground: "#F167BF",
//     bellIcon: "#FFFFFF",
//     elements: {
//       notification: "bg-red rounded-lg shadow-sm hover:shadow-md hover:bg-gray-50",
//       bellIcon: "bg-white",
//       borderRadius: "round-lg",
//     },
//   },
// };

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const metadata = {
//   title: "Novu Next.js Quickstart",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NovuProvider
          applicationIdentifier="Q9j-2L1WHqKP"
          subscriberId="e7b9d077-b16f-4c26-8382-4caf4b0ac084"
        >
          <nav className="flex justify-between items-center p-4 gap-4 h-16">
            <InboxWithBell />
          </nav>
          {children}
        </NovuProvider>
      </body>
    </html>
  );
}
